stages:
  - build

variables:
  DOCKERHUB_USERNAME: $CI_REGISTRY_USER
  DOCKERHUB_PASSWORD: $CI_JOB_TOKEN

before_script:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: python:3.9-slim-buster
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m unittest discover tests
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker logout $CI_REGISTRY
    - python app.py
  only:
    - master
