name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8
      run: |
        python -m pip install flake8
        flake8 .

    - name: Run Tests
      run: |
        python -m unittest discover tests

    - name: Build Docker image
      run: docker build -t sgerx/flask_hello-world_ci-cd:latest .

  app_run_and_stop:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run Flask application and Stop after 10 seconds
      run: |
        docker run -d -p 5000:5000 --name flask-app sgerx/flask_hello-world_ci-cd
        sleep 10
        curl -X POST http://127.0.0.1:5000/shutdown
      if: always()


  bash_run_and_stop:
    runs-on: ubuntu-latest
    needs: build

    - name: Set execute permission for entrypoint.sh
      run: chmod +x /app/entrypoint.sh

    - name: Run Tests and Flake8 using entrypoint.sh
      run: bash /app/entrypoint.sh


  push:
    runs-on: ubuntu-latest
    needs: [app_run_and_stop, bash_run_and_stop]

    steps:
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push sgerx/flask_hello-world_ci-cd:latest
