name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: |
          python -m pip install flake8
          flake8 .

      - name: Run Tests
        run: |
          python -m unittest discover tests

      - name: Build Docker image
        run: |
          docker build -t sgerx/flask_hello-world_ci-cd:latest .

  docker_run_and_stop:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Flask application and wait 10 seconds
        run: |
          CONTAINER_ID=$(docker run -d -p 5000:5000 --name flask-app sgerx/flask_hello-world_ci-cd)
          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
          sleep 10

      - name: Stop the Docker container
        run: docker stop $CONTAINER_ID
        if: always()

  app_run_and_stop:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Flask application and Stop after 10 seconds
        run: |
          python app.py > /dev/null 2>&1 &
          sleep 10
          curl -X POST http://127.0.0.1:5000/shutdown
        if: always()

  push:
    runs-on: ubuntu-latest
    needs: [docker_run_and_stop, app_run_and_stop]

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sgerx/flask_hello-world_ci-cd:latest
